version: '3.7'
services:
  python-app:
    image: anomalies-module:v1
    restart: always
    container_name: "anomalyModule"
    volumes:
      - ./anomalyDetection.py:/home/anomalyDetection.py
      - ./model:/home/model
      - ./inputs:/home/inputs
    stdin_open: true
    tty: true
    ports:
      - "1883"
    networks:
      net:
        ipv4_address: 172.18.0.176
    command: /bin/sh -c 'python /home/anomalyDetection.py'
networks:
  net:
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
